import { useTranslation } from 'react-i18next';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { FormField } from '@supershop/ui';
import { useSaveSettings } from '../hooks';
import { Checkbox, Select } from './controls';

// Digit samples are generated by Intl, never typed by hand.
const SAMPLE = 1234567890;
const digits = (system) =>
  new Intl.NumberFormat('ar-SA', { numberingSystem: system, useGrouping: false }).format(SAMPLE);

/** Storefront language behavior: auto-detect and Arabic digit style (save on change). */
export function StorefrontOptionsCard({ settings, canEdit }) {
  const { t } = useTranslation();
  const save = useSaveSettings();
  const value = (key) => settings?.find((s) => s.key === key)?.value;
  const set = (key, v) => save.mutate([{ key, value: v }]);

  return (
    <Card>
      <CardHeader>
        <CardTitle>
          <h2>{t('languages.storefront.title')}</h2>
        </CardTitle>
        <CardDescription>{t('languages.storefront.description')}</CardDescription>
      </CardHeader>
      <CardContent className="grid gap-5">
        <Checkbox
          id="autoDetect"
          label={t('languages.storefront.autoDetect')}
          description={t('languages.storefront.autoDetectHelp')}
          checked={Boolean(value('i18n.autoDetect'))}
          disabled={!canEdit || save.isPending}
          onChange={(e) => set('i18n.autoDetect', e.target.checked)}
        />
        <FormField
          label={t('languages.storefront.digits')}
          description={t('languages.storefront.digitsHelp')}
        >
          <Select
            className="max-w-xs"
            value={value('i18n.digitStyle') ?? 'latn'}
            disabled={!canEdit || save.isPending}
            onChange={(e) => set('i18n.digitStyle', e.target.value)}
          >
            <option value="latn">
              {t('languages.storefront.digitsWestern', { sample: digits('latn') })}
            </option>
            <option value="arab">
              {t('languages.storefront.digitsArabic', { sample: digits('arab') })}
            </option>
          </Select>
        </FormField>
      </CardContent>
    </Card>
  );
}
