import 'server-only';
import { DEFAULT_LOCALE, isLocale } from './config.js';
import { translate, translator } from './translate.js';
import { apiGet } from '@/lib/api';

/**
 * UI dictionaries (server-side). English is the authored source; other languages are GENERATED by
 * `npm run i18n:translate` and verified by `npm run i18n:check` (CI) — never hand-edited
 * (CLAUDE.md §5.7). Each language is a separate dynamic import (loaded only when used); any key
 * missing from a language falls back to English, so the site always renders.
 */
const loaders = {
  en: () => import('./dictionaries/en.json').then((m) => m.default),
  ar: () => import('./dictionaries/ar.json').then((m) => m.default),
};

const isObject = (v) => v && typeof v === 'object' && !Array.isArray(v);

/** Deep merge: `over` wins; `base` fills gaps. */
export function mergeFallback(base, over) {
  const out = { ...base };
  for (const [k, v] of Object.entries(over ?? {})) {
    out[k] = isObject(v) && isObject(base?.[k]) ? mergeFallback(base[k], v) : v;
  }
  return out;
}

/** `{ 'a.b': 'x' }` → `{ a: { b: 'x' } }` */
function unflatten(flat) {
  const out = {};
  for (const [key, value] of Object.entries(flat)) {
    const parts = key.split('.');
    let node = out;
    for (const p of parts.slice(0, -1)) node = node[p] = isObject(node[p]) ? node[p] : {};
    node[parts.at(-1)] = value;
  }
  return out;
}

/**
 * Human corrections made in Admin → Settings → Languages (stored in the API, applied on top of the
 * generated file). Cached 60 s (tag `ui-overrides`); never fails the page — no overrides on error.
 * @param {string} lang
 */
export async function getUiOverrides(lang) {
  try {
    const res = await apiGet(`/api/v1/i18n/ui-overrides/storefront/${lang}`, {
      tags: ['ui-overrides'],
    });
    return unflatten(res.data ?? {});
  } catch {
    return {};
  }
}

/**
 * Dictionary for a language: English ← generated `<lang>.json` ← admin overrides.
 * @param {string} lang
 */
export async function getDictionary(lang) {
  const base = await loaders[DEFAULT_LOCALE]();
  if (!isLocale(lang) || lang === DEFAULT_LOCALE) return base;
  const [generated, overrides] = await Promise.all([loaders[lang](), getUiOverrides(lang)]);
  return mergeFallback(mergeFallback(base, generated), overrides);
}

/** Server components: `const t = await getT(lang); t('home.title', { store })`. */
export async function getT(lang) {
  return translator(await getDictionary(lang));
}

export { translate, translator };
