import 'server-only';
import { DEFAULT_LOCALE, isLocale } from './config.js';
import { translate, translator } from './translate.js';

/**
 * UI dictionaries (server-side). English is the authored source; other languages are GENERATED by
 * `npm run i18n:translate` and verified by `npm run i18n:check` (CI) — never hand-edited
 * (CLAUDE.md §5.7). Each language is a separate dynamic import (loaded only when used); any key
 * missing from a language falls back to English, so the site always renders.
 */
const loaders = {
  en: () => import('./dictionaries/en.json').then((m) => m.default),
  ar: () => import('./dictionaries/ar.json').then((m) => m.default),
};

const isObject = (v) => v && typeof v === 'object' && !Array.isArray(v);

/** Deep merge: `over` wins; `base` fills gaps. */
export function mergeFallback(base, over) {
  const out = { ...base };
  for (const [k, v] of Object.entries(over ?? {})) {
    out[k] = isObject(v) && isObject(base?.[k]) ? mergeFallback(base[k], v) : v;
  }
  return out;
}

/** @param {string} lang */
export async function getDictionary(lang) {
  const base = await loaders[DEFAULT_LOCALE]();
  if (!isLocale(lang) || lang === DEFAULT_LOCALE) return base;
  return mergeFallback(base, await loaders[lang]());
}

/** Server components: `const t = await getT(lang); t('home.title', { store })`. */
export async function getT(lang) {
  return translator(await getDictionary(lang));
}

export { translate, translator };
