import 'server-only';
import { DEFAULT_LOCALE, isLocale } from './config.js';

/**
 * UI dictionaries (server-side). English is the authored source; `ar.json` is GENERATED by the
 * translation pipeline (P0.11: `npm run i18n:translate`) — never hand-edited (CLAUDE.md §5.7).
 * Any key missing from a language falls back to English, so the site always renders.
 */
const loaders = {
  en: () => import('./dictionaries/en.json').then((m) => m.default),
  ar: () => import('./dictionaries/ar.json').then((m) => m.default),
};

const isObject = (v) => v && typeof v === 'object' && !Array.isArray(v);

/** Deep merge: `over` wins; `base` fills gaps. */
export function mergeFallback(base, over) {
  const out = { ...base };
  for (const [k, v] of Object.entries(over ?? {})) {
    out[k] = isObject(v) && isObject(base?.[k]) ? mergeFallback(base[k], v) : v;
  }
  return out;
}

/** @param {string} lang */
export async function getDictionary(lang) {
  const base = await loaders[DEFAULT_LOCALE]();
  if (!isLocale(lang) || lang === DEFAULT_LOCALE) return base;
  return mergeFallback(base, await loaders[lang]());
}

/**
 * Looks up `a.b.c` and interpolates `{{vars}}`. Missing key → the key itself (visible in QA, never crashes).
 * @param {object} dict
 * @param {string} key
 * @param {Record<string, string | number>} [vars]
 */
export function translate(dict, key, vars) {
  const value = key.split('.').reduce((o, k) => (o == null ? undefined : o[k]), dict);
  if (typeof value !== 'string') return key;
  return vars
    ? value.replace(/\{\{(\w+)\}\}/g, (m, name) => (name in vars ? String(vars[name]) : m))
    : value;
}

/** Binds a dictionary: `const t = translator(dict); t('home.title', { store })`. */
export const translator = (dict) => (key, vars) => translate(dict, key, vars);
