'use client';

import { usePathname } from 'next/navigation';
import { localizePath, splitLocale } from '@/i18n/config';
import { LANG_COOKIE, LANG_COOKIE_MAX_AGE } from '@/i18n/negotiate';

/** Persists the visitor's explicit language choice (read by the proxy on later visits). */
function rememberLanguage(code) {
  document.cookie = `${LANG_COOKIE}=${code}; path=/; max-age=${LANG_COOKIE_MAX_AGE}; samesite=lax`;
}

/**
 * Header EN/AR switcher (CLAUDE.md §5.7). A plain link to the SAME page in the other language
 * (crawlable, works without JS); on click it remembers the choice in the `lang` cookie and keeps
 * the query string/hash. Labels are native language names generated by Intl (never hand-written).
 *
 * @param {{ lang: string, languages: { code: string, nativeName: string }[], label: string }} props
 */
export function LanguageSwitcher({ lang, languages, label }) {
  const pathname = usePathname() ?? '/';
  const { path } = splitLocale(pathname);
  const others = languages.filter((l) => l.code !== lang);

  const remember = (code, event) => {
    rememberLanguage(code);
    const { search, hash } = window.location;
    if (search || hash) {
      event.preventDefault();
      window.location.assign(`${localizePath(path, code)}${search}${hash}`);
    }
  };

  return (
    <nav aria-label={label} className="flex items-center gap-2 text-sm">
      {others.map((l) => (
        <a
          key={l.code}
          href={localizePath(path, l.code)}
          hrefLang={l.code}
          lang={l.code}
          onClick={(e) => remember(l.code, e)}
          // System font for the other language's name: rendering one word must not download that
          // language's web font (e.g. 166 KB Arabic font on every English page view).
          className="rounded-md border px-3 py-1.5 font-medium [font-family:system-ui,sans-serif] hover:bg-muted"
        >
          {l.nativeName}
        </a>
      ))}
    </nav>
  );
}
