import { PERMISSIONS as P } from '@supershop/shared';

/**
 * Seeded role templates (inserted once, then fully admin-editable; never overwritten by re-seeding).
 * Super-admin is NOT a role — it is an explicit, audited flag on the staff record.
 * Principle of least privilege: each template holds only what the job needs.
 */
export const DEFAULT_ROLES = Object.freeze([
  {
    systemKey: 'store_manager',
    name: 'Store Manager',
    description: 'Runs a branch: sales, stock, orders, returns, shifts and branch reports.',
    allBranches: false,
    permissions: [
      P.DASHBOARD_VIEW,
      P.PRODUCT_VIEW,
      P.PRODUCT_UPDATE,
      P.PRODUCT_VIEW_COST,
      P.INVENTORY_VIEW,
      P.INVENTORY_ADJUST,
      P.INVENTORY_TRANSFER,
      P.INVENTORY_RECEIVE,
      P.PURCHASE_VIEW,
      P.PURCHASE_MANAGE,
      P.BRANCH_VIEW,
      P.ORDER_VIEW,
      P.ORDER_UPDATE,
      P.ORDER_CANCEL,
      P.ORDER_REFUND,
      P.POS_SELL,
      P.POS_DISCOUNT,
      P.POS_PRICE_OVERRIDE,
      P.POS_VOID,
      P.SHIFT_OPEN,
      P.SHIFT_CLOSE,
      P.SHIFT_VIEW,
      P.SHIFT_CASH_MOVEMENT,
      P.RETURN_CREATE,
      P.RETURN_APPROVE,
      P.CUSTOMER_VIEW,
      P.CUSTOMER_MANAGE,
      P.LOYALTY_VIEW,
      P.LOYALTY_ADJUST,
      P.REPORT_VIEW,
      P.STAFF_VIEW,
    ],
  },
  {
    systemKey: 'cashier',
    name: 'Cashier',
    description: 'Sells at the POS in assigned branches, opens/closes own shift, starts returns.',
    allBranches: false,
    permissions: [
      P.POS_SELL,
      P.SHIFT_OPEN,
      P.SHIFT_CLOSE,
      P.SHIFT_VIEW,
      P.RETURN_CREATE,
      P.PRODUCT_VIEW,
      P.INVENTORY_VIEW,
      P.CUSTOMER_VIEW,
      P.LOYALTY_VIEW,
      P.ORDER_VIEW,
    ],
  },
  {
    systemKey: 'inventory_clerk',
    name: 'Inventory Clerk',
    description: 'Receives, counts, adjusts and transfers stock in assigned branches.',
    allBranches: false,
    permissions: [
      P.PRODUCT_VIEW,
      P.INVENTORY_VIEW,
      P.INVENTORY_ADJUST,
      P.INVENTORY_TRANSFER,
      P.INVENTORY_RECEIVE,
      P.PURCHASE_VIEW,
      P.PURCHASE_MANAGE,
      P.BRANCH_VIEW,
    ],
  },
  {
    systemKey: 'catalog_editor',
    name: 'Catalog Editor',
    description: 'Maintains products, categories, brands, suppliers and media.',
    allBranches: true,
    permissions: [
      P.PRODUCT_VIEW,
      P.PRODUCT_CREATE,
      P.PRODUCT_UPDATE,
      P.PRODUCT_IMPORT,
      P.PRODUCT_EXPORT,
      P.CATEGORY_MANAGE,
      P.BRAND_MANAGE,
      P.SUPPLIER_MANAGE,
      P.MEDIA_MANAGE,
      P.INVENTORY_VIEW,
    ],
  },
  {
    systemKey: 'content_editor',
    name: 'Content Editor',
    description: 'Builds and publishes storefront pages, menus and SEO content.',
    allBranches: true,
    permissions: [
      P.PAGE_VIEW,
      P.PAGE_MANAGE,
      P.PAGE_PUBLISH,
      P.MENU_MANAGE,
      P.SEO_MANAGE,
      P.MEDIA_MANAGE,
    ],
  },
  {
    systemKey: 'marketing',
    name: 'Marketing',
    description: 'Runs campaigns and tracking integrations; views customers and reports.',
    allBranches: true,
    permissions: [
      P.DASHBOARD_VIEW,
      P.CAMPAIGN_VIEW,
      P.CAMPAIGN_MANAGE,
      P.CAMPAIGN_SEND,
      P.TRACKING_MANAGE,
      P.CUSTOMER_VIEW,
      P.CUSTOMER_EXPORT,
      P.REPORT_VIEW,
    ],
  },
  {
    systemKey: 'accountant',
    name: 'Accountant',
    description:
      'Read-only finance view across all branches: orders, shifts, costs, reports, exports.',
    allBranches: true,
    permissions: [
      P.DASHBOARD_VIEW,
      P.ORDER_VIEW,
      P.ORDER_EXPORT,
      P.PRODUCT_VIEW,
      P.PRODUCT_VIEW_COST,
      P.INVENTORY_VIEW,
      P.PURCHASE_VIEW,
      P.SHIFT_VIEW,
      P.REPORT_VIEW,
      P.REPORT_EXPORT,
      P.BRANCH_VIEW,
    ],
  },
  {
    systemKey: 'customer_support',
    name: 'Customer Support',
    description: 'Handles online orders and customer requests.',
    allBranches: true,
    permissions: [
      P.ORDER_VIEW,
      P.ORDER_UPDATE,
      P.ORDER_CANCEL,
      P.CUSTOMER_VIEW,
      P.CUSTOMER_MANAGE,
      P.LOYALTY_VIEW,
      P.RETURN_CREATE,
      P.PRODUCT_VIEW,
      P.INVENTORY_VIEW,
    ],
  },
]);
