import { createHash } from 'node:crypto';

/**
 * Pure helpers for the UI string pipeline (unit-tested; no I/O).
 * Dictionaries are nested JSON; internally they're handled as flat `a.b.c` → string maps.
 */

export const hash = (s) => createHash('sha256').update(s, 'utf8').digest('hex').slice(0, 16);

/** { a: { b: 'x' } } → { 'a.b': 'x' } (only string leaves; other types are reported by validate). */
export function flatten(obj, prefix = '', out = {}) {
  for (const [k, v] of Object.entries(obj ?? {})) {
    const key = prefix ? `${prefix}.${k}` : k;
    if (v && typeof v === 'object' && !Array.isArray(v)) flatten(v, key, out);
    else out[key] = v;
  }
  return out;
}

/** Inverse of flatten, keeping the key ORDER of `orderFrom` (the English file) for stable diffs. */
export function unflatten(flat, orderFrom) {
  const out = {};
  for (const key of Object.keys(orderFrom)) {
    if (!(key in flat)) continue;
    const parts = key.split('.');
    let node = out;
    for (const p of parts.slice(0, -1)) node = node[p] ??= {};
    node[parts.at(-1)] = flat[key];
  }
  return out;
}

/** Interpolation placeholders used by our t() implementations: {{name}} (i18next & storefront). */
export const placeholders = (s) =>
  typeof s === 'string' ? [...s.matchAll(/\{\{\s*([\w.]+)\s*\}\}/g)].map((m) => m[1]).sort() : [];

const sameList = (a, b) => a.length === b.length && a.every((x, i) => x === b[i]);

/**
 * Compares a target dictionary with the source and lock.
 * @param {Record<string, unknown>} source  flat en
 * @param {Record<string, unknown>} target  flat target
 * @param {Record<string, { src: string, out?: string, mode?: 'manual', status?: 'failed' }>} lock
 *   lock entries for this language
 * @returns {{ toTranslate: string[], problems: { key: string, issue: string }[], warnings: { key: string, issue: string }[] }}
 *   toTranslate: keys the translate command should (re)generate
 *   problems:    everything the CI check must fail on (pipeline not run, bypassed, or broken output)
 *   warnings:    the engine could not translate the CURRENT English (pipeline ran; English is shown
 *                until a manual override or a better provider fixes it)
 */
export function diffCatalog(source, target, lock) {
  const toTranslate = [];
  const problems = [];
  const warnings = [];
  for (const [key, en] of Object.entries(source)) {
    if (typeof en !== 'string') {
      problems.push({ key, issue: 'source value is not a string' });
      continue;
    }
    const value = target[key];
    const entry = lock[key];
    const manual = entry?.mode === 'manual';
    if (
      (typeof value !== 'string' || value.trim() === '') &&
      entry?.status === 'failed' &&
      entry.src === hash(en)
    ) {
      toTranslate.push(key); // retried on every translate run (engine/glossary may have improved)
      warnings.push({
        key,
        issue: 'engine could not translate — English shown; add a manual override',
      });
    } else if (typeof value !== 'string' || value.trim() === '') {
      toTranslate.push(key);
      problems.push({ key, issue: 'missing' });
    } else if (!entry) {
      toTranslate.push(key);
      problems.push({ key, issue: 'not generated by the pipeline (no lock entry)' });
    } else if (entry.out !== hash(value)) {
      toTranslate.push(key);
      problems.push({
        key,
        issue: 'edited by hand (output hash mismatch) — use a manual override instead',
      });
    } else if (!manual && entry.src !== hash(en)) {
      toTranslate.push(key);
      problems.push({ key, issue: 'stale (English changed)' });
    } else if (!sameList(placeholders(en), placeholders(value))) {
      toTranslate.push(key);
      problems.push({
        key,
        issue: `placeholder mismatch: en {{${placeholders(en)}}} vs {{${placeholders(value)}}}`,
      });
    }
  }
  for (const key of Object.keys(target)) {
    if (!(key in source)) problems.push({ key, issue: 'orphan (no longer in English)' });
  }
  return { toTranslate, problems, warnings };
}

/** Removes block and line comments (keeps `://` in URLs) so documentation examples aren't scanned. */
export const stripComments = (code) =>
  code.replace(/\/\*[\s\S]*?\*\//g, '').replace(/(^|[^:])\/\/.*$/gm, '$1');

/**
 * Finds literal `t('a.b')` / `t("a.b")` calls (also `i18n.t`, `translate(dict, 'a.b')` excluded).
 * Dynamic keys (`t(\`errors.${code}\`)`) are intentionally not checked.
 * @param {string} code
 */
export function usedKeys(code) {
  return [...stripComments(code).matchAll(/(?<![\w.$])t\(\s*['"]([A-Za-z][\w.-]*)['"]/g)].map(
    (m) => m[1],
  );
}
