import { config } from '../../core/config.js';
import { createLocalStorage } from './local.js';

/**
 * File storage adapters (CLAUDE.md §2.4, §5.1). Business code stores only the `key`; the public
 * URL is computed at read time, so moving files to S3/CDN needs no DB migration.
 *
 * Interface:
 *   {
 *     name: string,
 *     put(key: string, body: Buffer, { contentType: string }): Promise<void>,
 *     delete(key: string): Promise<void>,          // missing file = success (idempotent)
 *     url(key: string): string,                    // public URL for the key
 *     staticHandler?(): import('express').RequestHandler   // only drivers the API itself serves
 *   }
 * Keys are generated by the server (`isSafeKey`), never taken from user input.
 * Adding a driver (S3-compatible: AWS, R2, MinIO, Spaces) = new file here + a branch below + an
 * env enum value; credentials stay in env, never in settings.
 */

export { isSafeKey } from './keys.js';

/**
 * @param {{ driver: string, localDir?: string, publicUrl: string }} cfg
 */
export function createStorage(cfg) {
  switch (cfg.driver) {
    case 'local':
      return createLocalStorage({ rootDir: cfg.localDir, publicUrl: cfg.publicUrl });
    default:
      throw new Error(`Unknown media storage driver: ${cfg.driver}`);
  }
}

let instance = null;
/** Process-wide storage from env config (tests replace it with `setStorage`). */
export function getStorage() {
  instance ??= createStorage({
    driver: config.MEDIA_STORAGE,
    localDir: config.MEDIA_LOCAL_DIR,
    publicUrl: config.MEDIA_PUBLIC_URL,
  });
  return instance;
}
export function setStorage(storage) {
  instance = storage;
}
