// @vitest-environment jsdom
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { beforeEach, describe, expect, it, vi } from 'vitest';

let pathname = '/';
vi.mock('next/navigation', () => ({ usePathname: () => pathname }));
const { LanguageSwitcher } = await import('@/components/layout/LanguageSwitcher');
const { languageOptions } = await import('@/i18n/config');

beforeEach(() => {
  document.cookie = 'lang=; max-age=0; path=/';
});

describe('LanguageSwitcher', () => {
  it('links to the same page in the other language with hreflang + lang attributes', () => {
    pathname = '/products/blue-shirt';
    render(<LanguageSwitcher lang="en" languages={languageOptions()} label="Language" />);
    const link = screen.getByRole('link');
    expect(link).toHaveAttribute('href', '/ar/products/blue-shirt');
    expect(link).toHaveAttribute('hreflang', 'ar');
    expect(link).toHaveAttribute('lang', 'ar');
    // Native name generated by Intl (Arabic script), not hand-written.
    expect(link.textContent).toBe(new Intl.DisplayNames(['ar'], { type: 'language' }).of('ar'));
    expect(link.textContent).toMatch(/\p{Script=Arabic}/u);
  });

  it('from Arabic, links back to the unprefixed English URL', () => {
    pathname = '/ar/products/blue-shirt';
    render(<LanguageSwitcher lang="ar" languages={languageOptions()} label="Language" />);
    expect(screen.getByRole('link', { name: 'English' })).toHaveAttribute(
      'href',
      '/products/blue-shirt',
    );
  });

  it('home page maps to /ar and back to /', () => {
    pathname = '/ar';
    render(<LanguageSwitcher lang="ar" languages={languageOptions()} label="Language" />);
    expect(screen.getByRole('link')).toHaveAttribute('href', '/');
  });

  it('remembers the choice in the lang cookie on click', async () => {
    pathname = '/';
    render(<LanguageSwitcher lang="en" languages={languageOptions()} label="Language" />);
    const link = screen.getByRole('link');
    link.addEventListener('click', (e) => e.preventDefault()); // jsdom can't navigate
    await userEvent.click(link);
    expect(document.cookie).toContain('lang=ar');
  });
});
