/**
 * UI string catalogs (CLAUDE.md §5.7). `en.json` is the ONLY file developers edit; target-language
 * files are generated by `npm run i18n:translate` and verified by `npm run i18n:check` (CI).
 *
 * - dir:      folder with `<lang>.json` files and the generated `i18n.lock.json`
 * - targets:  generated languages. Admin UI stays English in v1 (add 'ar' here to enable it).
 * - scan:     source folders checked for `t('key')` calls whose key is missing from en.json
 */
export const SOURCE = 'en';

export const CATALOGS = [
  {
    name: 'storefront',
    dir: 'apps/storefront/src/i18n/dictionaries',
    targets: ['ar'],
    scan: ['apps/storefront/src'],
  },
  {
    name: 'admin',
    dir: 'apps/admin/src/locales',
    targets: [],
    scan: ['apps/admin/src'],
  },
];
