import i18n from 'i18next';
import { initReactI18next, useTranslation } from 'react-i18next';
import en from '@/locales/en.json';

/**
 * UI strings: English source only (CLAUDE.md §5.7). Use `t('key')` — never hardcode text.
 * English is bundled; other languages are generated by `npm run i18n:translate` (enable by adding
 * the language to tools/i18n/catalogs.config.js) and loaded lazily as separate chunks.
 * The admin UI stays English in v1.
 * API errors arrive as stable codes → `errors.<CODE>`; validation messages are `validation.*` keys.
 */
void i18n.use(initReactI18next).init({
  resources: { en: { translation: en } },
  lng: 'en',
  fallbackLng: 'en',
  initAsync: false,
  interpolation: { escapeValue: false }, // React already escapes
  returnNull: false,
});

// One lazy chunk per generated language file (never bundled up front).
const lazyLocales = import.meta.glob([
  '../locales/*.json',
  '!../locales/en.json',
  '!../locales/i18n.lock.json',
]);

/**
 * Switches UI language, downloading its strings on first use. Sets <html lang dir>.
 * @param {string} lng
 */
export async function loadLanguage(lng) {
  if (lng !== 'en' && !i18n.hasResourceBundle(lng, 'translation')) {
    const loader = lazyLocales[`../locales/${lng}.json`];
    if (!loader) throw new Error(`No UI strings for "${lng}" — run npm run i18n:translate`);
    const mod = await loader();
    i18n.addResourceBundle(lng, 'translation', mod.default, true, true);
  }
  await i18n.changeLanguage(lng);
  document.documentElement.lang = lng;
  document.documentElement.dir = i18n.dir(lng);
}

/** Same API as the storefront: `const t = useT(); t('auth.signIn')`. */
export const useT = () => useTranslation().t;

/**
 * Message for an API error or a validation key, with a safe generic fallback.
 * @param {(key: string, opts?: object) => string} t
 * @param {unknown} error
 */
export function errorMessage(t, error) {
  const code = /** @type {any} */ (error)?.code;
  if (code === 'NETWORK_ERROR') return t('errors.network');
  return code && i18n.exists(`errors.${code}`) ? t(`errors.${code}`) : t('errors.generic');
}

/** Translates a zod/react-hook-form message that is an i18n key; otherwise a generic message. */
export const fieldMessage = (t, message) =>
  message && i18n.exists(message) ? t(message) : message ? t('validation.invalidType') : undefined;

export default i18n;
